import cv2
import mediapipe as mp
import numpy as np
import pickle
import time
from pathlib import Path

# --- Configuration ---
# The model file generated by train_gesture_classifier.py
# Change path to file on your computer
MODEL_PATH = '/Users/allen/Desktop/argz-gesture-based-calculator/src/argz-gesture-based-calculator/gesture_classifier_model.pkl' 

# --- Index Finger Landmark Indices (5, 6, 7, 8) ---
# 5: Index finger base (MCP), 6: PIP, 7: DIP, 8: Tip
INDEX_FINGER_LANDMARKS = [5, 6, 7, 8] 

# Initialize MediaPipe Hands solution
mp_hands = mp.solutions.hands
hands = mp_hands.Hands(
    static_image_mode=False,
    max_num_hands=2,  # <--- Set to 2 to detect both hands
    min_detection_confidence=0.7,
    min_tracking_confidence=0.5
)
mp_drawing = mp.solutions.drawing_utils

def load_classifier(model_path):
    """Loads the trained model and label map from the pickle file."""
    try:
        with open(model_path, 'rb') as f:
            data = pickle.load(f)
            model = data['model']
            label_map = data['label_map']
            
            # Reverse the map for display purposes
            label_reverse_map = {v: k for k, v in label_map.items()}
            
            print(f"Model loaded successfully. Recognized gestures: {list(label_map.keys())}")
            return model, label_reverse_map
    except FileNotFoundError:
        print(f"Error: Model file not found at {model_path}. Please run train_gesture_classifier.py first.")
        exit()
    except Exception as e:
        print(f"Error loading model: {e}")
        exit()

def extract_index_finger_features_single(hand_landmarks):
    """
    Extracts and normalizes the 4 index finger landmarks relative to the wrist (landmark 0) 
    for a single hand, matching the training script logic.
    
    Returns: A 12-element numpy array.
    """
    # 1. Extract wrist landmark (index 0) for normalization
    wrist_x = hand_landmarks.landmark[0].x
    wrist_y = hand_landmarks.landmark[0].y
    wrist_z = hand_landmarks.landmark[0].z
    
    normalized_features = []
    
    # 2. Iterate ONLY through the index finger landmarks and normalize
    for i in INDEX_FINGER_LANDMARKS:
        landmark = hand_landmarks.landmark[i]
        
        # Calculate coordinates relative to the wrist
        rel_x = landmark.x - wrist_x
        rel_y = landmark.y - wrist_y
        rel_z = landmark.z - wrist_z
        
        normalized_features.extend([rel_x, rel_y, rel_z])

    return np.array(normalized_features)


def extract_dual_index_finger_features(results):
    """
    Extracts features for up to two hands (index fingers only).
    Pads with zeros if only one hand is found, resulting in a 24-element vector.

    Args:
        results: The MediaPipe hands processing results object.

    Returns:
        np.array or None: A flattened 24-element feature vector, or None if no hands detected.
    """
    all_features = []
    num_hands_detected = 0

    if results.multi_hand_landmarks:
        num_hands_detected = len(results.multi_hand_landmarks)
        
        for i in range(min(2, num_hands_detected)):
            hand_landmarks = results.multi_hand_landmarks[i]
            features = extract_index_finger_features_single(hand_landmarks)
            all_features.append(features)
    
    if num_hands_detected == 0:
        return None
    
    # Padding: If only one hand is detected, append 12 zeros for the missing hand
    if num_hands_detected == 1:
        # 4 index finger landmarks * 3 coordinates = 12 zero padding elements
        padding = np.zeros(12, dtype=np.float32) 
        all_features.append(padding)

    # Concatenate features into a single 24-element vector and reshape for the classifier
    return np.concatenate(all_features).reshape(1, -1)


def main():
    # Load the trained model and labels
    model, label_reverse_map = load_classifier(MODEL_PATH)

    # Initialize webcam (usually 0)
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("Error: Cannot open webcam.")
        return

    gesture_text = "Waiting for hand..."
    
    print("Webcam started, detecting two hands. Press 'q' to exit.")

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # Flip the frame horizontally for a more intuitive view (like a mirror)
        frame = cv2.flip(frame, 1)
        
        # Convert the BGR image to RGB
        image_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        
        # Process the image and find hands
        image_rgb.flags.writeable = False
        results = hands.process(image_rgb)
        image_rgb.flags.writeable = True

        # Convert back to BGR for display
        frame = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2BGR)

        
        if results.multi_hand_landmarks:
            
            # 1. Extract features and predict using the dual-hand logic
            feature_vector = extract_dual_index_finger_features(results)
            
            if feature_vector is not None and feature_vector.size == 24:
                # Predict the gesture
                prediction_id = model.predict(feature_vector)[0]
                gesture_text = f"Gesture: {label_reverse_map.get(prediction_id, 'UNKNOWN')}"
            
            # 2. Draw only the index finger landmarks for all detected hands
            INDEX_FINGER_CONNECTIONS = [(5, 6), (6, 7), (7, 8)]
            
            for hand_landmarks in results.multi_hand_landmarks:
                
                # Draw connections only for the index finger
                for connection in INDEX_FINGER_CONNECTIONS:
                    start_point = hand_landmarks.landmark[connection[0]]
                    end_point = hand_landmarks.landmark[connection[1]]
                    
                    h, w, _ = frame.shape
                    start_px = mp_drawing._normalized_to_pixel_coordinates(start_point.x, start_point.y, w, h)
                    end_px = mp_drawing._normalized_to_pixel_coordinates(end_point.x, end_point.y, w, h)

                    if start_px and end_px:
                        cv2.line(frame, start_px, end_px, (0, 255, 0), 3) # Green line
                
                # Draw the index finger points themselves
                for i in INDEX_FINGER_LANDMARKS:
                    landmark = hand_landmarks.landmark[i]
                    h, w, _ = frame.shape
                    point_px = mp_drawing._normalized_to_pixel_coordinates(landmark.x, landmark.y, w, h)
                    if point_px:
                        cv2.circle(frame, point_px, 5, (0, 0, 255), -1) # Red dot

        else:
            gesture_text = "No Hand Detected"

        # Display the prediction text on the frame
        cv2.putText(
            frame, 
            gesture_text, 
            (10, 30), 
            cv2.FONT_HERSHEY_SIMPLEX, 
            1, 
            (255, 255, 255), # White text
            2, 
            cv2.LINE_AA
        )

        cv2.imshow('Dual Index Finger Gesture Recognition', frame)

        # Break the loop on 'q' key press
        if cv2.waitKey(5) & 0xFF == ord('q'):
            break

    # Release resources
    cap.release()
    cv2.destroyAllWindows()
    hands.close()

if __name__ == '__main__':
    # Dependencies: pip install opencv-python mediapipe numpy scikit-learn
    main()
